-- Insert only missing products (IDs 12-27)
-- Run this ONCE in Supabase Dashboard -> SQL Editor -> New query
-- Skips any IDs that already exist

insert into public.products (
  id,
  name,
  description,
  price,
  lang,
  series,
  image,
  thumbnails,
  in_stock,
  rating,
  reviews
) values
  (
    12,
    'Charizard UPC',
    null,
    135.00,
    'Eng',
    'Sword & Shield',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuC26fAOHF9XTupH5f68zPpSav12fTxGPkFXaSkmgwUBYVpnCHo7d6hW7_U81Q5dPZ2HEuFCBHUT6H8hWgmLbfKAS27rfkwVFg7Je77kY0CTLT7zba0Pjx2YiFX6Mgd_1kuGX-5JVEiIbFqnA6J4fBndZxURdIkPqnjZd3caWzk666bIPtLz2bC_YPM0FwET_sJs_t94ch67rBN4PzpNB0LV18WUb7rP475Nz-WvAZ-Fz6W3WmtPv8hF7d7lAaE53wKxFtcXJGnk-Bk',
    array[]::text[],
    true,
    null,
    null
  ),
  (
    13,
    'Scarlet & Violet: 151 Booster Box',
    'Relive the original Kanto journey with the Scarlet & Violet: 151 Booster Box. This sealed box contains 36 booster packs, each offering a chance to pull rare illustration cards of the original 151 Pokémon including Charizard ex, Blastoise ex, and Venusaur ex.',
    140.00,
    'Jpn',
    'Scarlet & Violet',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDEg0FL8fVF3SrWrTznZHG98V0sPOZFKZoks7X4cw79L0PPs5OHBPipPbUJpw_axQlbuoP5_65a3ODL92M1qnQ1ERZNgjpf47Fo6nd2sFw154XySCt_SgLH0DSJcGO98UvzFJsPon8JsPvLDVw-5Feds2U3EefB6-LJ_Io9751dm6oB2w0E_s440tYev3btEKmfVar2bk496cxCQkhcxcceSMGmzEEmr3fJavVLDhKUYm2iK5FQmag7DUYAPCJo4mz9TUTsRdktmf0',
    array[
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAO7GWKsD6tObmZxAi_owQSpzZqgP82zmrX_RwcG_c-D57F4o16o-EnYVy7gADjZy0URXyNzC9pL1o7RvcSfyuW_I9x_JgNy5HssGAn5tCc8UwCINYiQPQdz5lZ-FHUg-szUuM4pTI7Vigmq4-zdLwDdowzkyF9yj0YLdU2zrQrQzRJtKFMH_m_mEZv6L_iGWfp82WY9s_fOH2X0pKSm3M04YvXXdhs0av9m2v8g_e5gVHd705fUEpiQCpXDqIV2agjsMvz2lA6CCo',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBUnyT9D-9dyyh5oc9TS1TcfkmUdaHH6XYUZjqubXLQrBJIzO7_vCdsYgy96zQpTzMV4eecRAzdsgIqEMDp8-l2Vq2cOJEWfjw-BGWgK2n7j5AhFlm1BDX_tNp2nP9Tnh_zF1LOJIbN476O3_J6MLk8QCYMAfjCPPpeFwY-JFbYfv2TUadsM2z6uTHLSz5B2to_XcUaYBtYQglvb9R5Msnbvi9rivTn12cewxlxEI6KAUnedQgfDSHdfUMePtQQeZeSOQgyH-mWuW8',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCuj2ROAdsVuhA6TWisBBCnY9YmjDVm-hPU8-7tAo98Lkf_OX_gO3KUpJZUuvrSS0TaWyOEEIrL7qMcMFSaGu9Kypc2Fc7p0X_8VoVQvtWR6zp5vDhNwIEwRij-rUhxOwnDVSJLSguziHM-mFBOdjAeuxdNNkh8Ts1UQQYPjJTtzqFdhUTT0M8_4MnNwINqyYX6IQ7H_l5tajLxT7c2VmvpfjOC-UVwlyz9OSZKM6HBKGJbKYitTrIRokCx0hUH_-l0napaH5h3BiQ',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuC7P3b4F19zHkW1zrzQ9Yvmc2W69qUcYzD03Pvs_pLO75XYzEqN5b-v6yhatcfZvUmAPbQ1dQEbSFM9uHkCuEEeaD3WqnvgbR7SaYPkT5V-5b6bMfROh9YyxAu6O_q-m4XxjzTuk3b2VPyCRy0sozOC9rud6Fbsz8JuxVtLRiXKdAMz0ifClvYGptWF79BUlzJA0i8dAteFAHgLSdpED1snu47hfdQVj29CvB-FxV1C5yhr3U0e6FvehEhnKEgn-ercAgI96-uy0j8',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCL28auKhuPEs2IIlXfIwC17D9FCo7XB6ppZpsjJ6oF6YMdlpx9gwqv_xhjZUcTmLk0xDx0iNV2OdKIgnaGQDxCc6PiVbaou1MyZ8fbJbA-YaukOCtR6llaMe6nZ-lX3bdBZVFe0xzul6pXibm5Onehf2IgVO6ZrUiN2bbZNTOQGHPXBBjFSX_pXQGu_0oAErFZnDLsrFL_BFDTo5NiS2GQpITssSmRnw0LEX6wEe2vbbjglppUHs4mxeV8C5gTr1nM09DnsCV997I'
    ],
    true,
    4.9,
    128
  ),
  (
    14,
    'Evolving Skies Booster Box',
    null,
    450.00,
    'Eng',
    'Sword & Shield',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBooVJEPhWsiSijLZFSZR3LMNNGivN8QyaxJHifLde6MpoahT-eqNZf_FvE0ZnYgoMTgdm7wA285cAVmZjC9QM8lfU-oEDW-xqpMcoqSTGpm3hdqBtBIOjf965npqEjSSA3d5KzdyThV1YmBRHjRYSc1DRh0-sKvkfB9B1IewoOSN6fx70R-zAqCqgv_csFQN3aaumnq2c_KTooGgLNFXVr6sTu5EpWzcyeNbqyblIjlEFceYxV4VyePn50DZV9Pv7lty3p-QdhIos',
    array[]::text[],
    true,
    null,
    null
  ),
  (
    15,
    'Lost Origin Booster Box English',
    null,
    130.00,
    'Eng',
    'Sword & Shield',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuA4oTk3dgcQEusVci9TT_KbLwthf5aMOHcUZnkt_CwKyYT5QKdojOOc2j-MzL-aXOov-T0M8P11FPFhnuXCFPwC4HJohFtyyFGqJd_FG0sD0xE0Ncf6NgW41UexUwNwWLNE2dR6v8MdZ286PpPWREyX160yg3CL33FoArQ547CFisGfkV0zofgP8kv7nX6T57BMedIUIROzR1lCTwSedjDDWMjQExSZdpLTtoy2fCcIoBpNkNF0cr1IgBVnx1-OiFQPfv6ODOkwms0',
    array[]::text[],
    true,
    null,
    null
  ),
  (
    16,
    'Paldea Evolved Booster Box',
    'Paldea Evolved brings the first partner Pokémon of the Paldea region to the TCG. This set features powerful new Pokémon ex and beautiful illustration rare cards.',
    125.00,
    'Eng',
    'Scarlet & Violet',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuC4KwVqKSwPUGOlvjpreBqF-nNiXkv2OmviQFtWmIPVpZOcMiXeegrfQ62yWCU-3bHS2cF5GGbAyUQkcrFwLmwUdtSA3931NSlul9As2l-wjBNzvVhhzD2hRps__fqiny2OzCf9PWM8i6tBvvN52cxuYAji1HR8QigjvgJsUeihP0m8b2qSRXPLD8x_2evVN1Mbcsf6HZGvV6d7qSx_nKQOc8wKHXBWCKFntCcFl0-AAQBIZqLe8phZQoeiWCVeNL5fhjAHYoeOzH8',
    array[]::text[],
    true,
    4.7,
    45
  ),
  (
    17,
    'Obsidian Flames Booster Box',
    'Red-hot embers illuminate the pitch-black night and sparks flare into an inferno as Charizard ex surges forth with newfound powers of darkness!',
    110.00,
    'Eng',
    'Scarlet & Violet',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuATY0O4QU6HrASu5KHXd11tu5SrdT5vtHbQn1jEywLhMGNRuotZNu5jrrmQWu8HHI1MUFPNpt4auaPkWzgPlzGc2QabK-mDXGa_Ce6wgn5YYYiDB6x_QMvrmTWQ4RhkCBhdNlebaEqEGlQAn2RRMqlCYK1MWXgvGSk3OOmk65beKRXAYjf0fX1FTgAGx6FMctDXLkmHhKBzb80trcifkr9lY9fB_HRxfHLFc-U5fn7bbnVlprZbXY15OECHnFdFctGB-M5Hq7rSS4w',
    array[]::text[],
    true,
    4.6,
    38
  ),
  (
    18,
    'Astral Radiance Booster Box',
    'Travel back to a land of myths, legends, and wilderness as Origin Forme Dialga VSTAR and Origin Forme Palkia VSTAR shape the very fabric of time and space!',
    99.00,
    'Eng',
    'Sword & Shield',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuCQX6l5PxeA3f3r_-4o-5Xu0QNzLC-VM3jSlyaz1aAev67mPdr7uhR-fSdYiUojEZjQY_2H_fIJ4nTyVuRHhnYpU5237QMKNzzo1CSWmbCugXDMTb2bvpWE8wCVHzQFZE4Gqe0wrUca1ncP_fg8TGHLq2A1Ub_BjeO79PQtQxLRf4zzlkIrHWWNVPObRnd4JXwH8oUJiVGwNKbWVgQpSRr8Ryn8m7jYBv_Usqc8sVwF_D-g6z4VX6MNxBmQdiTIZ7wOepQc32DCCns',
    array[]::text[],
    true,
    4.5,
    52
  ),
  (
    19,
    'Skyridge Booster Box',
    'The final set produced by Wizards of the Coast. A legendary masterpiece for any serious collector. Features the iconic Crystal Pokémon.',
    45000.00,
    'Eng',
    'Vintage',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuArsSwDAgYjbP0qJUwbWDdjronk6f1Qq0qjYozYeEEh5LZOI2_CfApOYh4FPwcJxcc0DaQP4hVuTCPzm-KRUJy9GNdT0gHSat7DQkhJpncbb4mKy13-HHPNDvVGx1s2Wr3e2aAoM2NSvm2iOeOd1Qx80VTV3Cy-j70yGCG5DYQjuGAsy0UZNaVLk4IOLjUywhYaafyL10ZTEP0KrjnpIkvC_zIUpKymGrM_4qdvv0hj5CtH-MMPPcnJQKJwh6UfHLKVy1HIc-kV9bg',
    array[]::text[],
    true,
    5.0,
    12
  ),
  (
    20,
    'Base Set (Unlimited) Booster Box',
    'Where it all began. The original 1999 Base Set booster box. A piece of history containing the most iconic cards in the franchise.',
    15000.00,
    'Eng',
    'Vintage',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBu3Q_G81gKl6hjWgJ2Bc7g19Dn2Zx7vc-o52fwase-txCqXMBfpF6FIvA1tHYcHGzH2pNglVpR2huxG24j88almRA7zVh4bhpGsMaM-xAlnu3VHI_zpT4qMXIXZMSamm97ChOb4oXvgjo2C061wbOsildWlEidhQKP6dlPM0xji124x9NwCDFWUOh4wwuD_nZX8hutgdn_g_uwTlRb6QPMNEZgqT27Z1fLZNPDIn1jB0DI96SV4qenNjuqKbAEPzVIIjI9wwsDChQ',
    array[]::text[],
    true,
    5.0,
    25
  ),
  (
    21,
    'Fossil First Edition Booster Box',
    'The third expansion of the Pokémon TCG. This First Edition box is a rare find from the earliest days of the game.',
    8500.00,
    'Eng',
    'Vintage',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBzYr2BT2ZXqpQOFJgFYtgbDIa2OyAOZed2AAiv5WIbuQ5DQwj47tVquEIeOU6PHh369InEAoeNaMO4viV3j-DtwJ8j3zgiSA1yfPMIDFxVhNAFLvMORCBFyMvb2tRKU09SZjNc1pABGvC_6tP9HsVK50ZuJ3BhJdlmKNwPwMIqJGYvvrxAmq7bdKtgC2NQDh3Qu-H9InSp6fR5SUsZRLaIHzJT8Fw1bdHyXP3u5vZOAv_0iSXko74vMRrXvJWgvq8X_EfTroOxsFg',
    array[]::text[],
    true,
    4.9,
    18
  ),
  (
    22,
    'Aquapolis Booster Box',
    'Part of the e-Card series, Aquapolis is known for its beautiful art and unique card designs. A true collector''s item.',
    22000.00,
    'Eng',
    'Vintage',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuCQX6l5PxeA3f3r_-4o-5Xu0QNzLC-VM3jSlyaz1aAev67mPdr7uhR-fSdYiUojEZjQY_2H_fIJ4nTyVuRHhnYpU5237QMKNzzo1CSWmbCugXDMTb2bvpWE8wCVHzQFZE4Gqe0wrUca1ncP_fg8TGHLq2A1Ub_BjeO79PQtQxLRf4zzlkIrHWWNVPObRnd4JXwH8oUJiVGwNKbWVgQpSRr8Ryn8m7jYBv_Usqc8sVwF_D-g6z4VX6MNxBmQdiTIZ7wOepQc32DCCns',
    array[]::text[],
    true,
    4.9,
    15
  ),
  (
    23,
    'Neo Discovery Booster Box',
    'The second set in the Neo series, introducing many Generation II Pokémon to the TCG. Features the mysterious Unown.',
    12500.00,
    'Eng',
    'Vintage',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuA-Klgd8n9EOYGtDEhZh3-lMpscD27tlv7S9F2VoNKGtiz_H5DQBl8Rayvm-xD73e_e_waYjERK3_GxFxFBlrT366wS6tQQo4p28IVCPlqrpJ1olAQVIp5oOF853N_9MgbxU6lv6bRciA4jQ52ZhmMcic953X2611qKaD-osIB7lWm5wicXQim9sfNMTKaOIDBSFYyl9euwrMUFWc6w52NsHeeHF8KiyWsb534SYMfs8LwvUoGxePyDt6NubrDt43csrJtINbxYmFw',
    array[]::text[],
    true,
    4.8,
    20
  ),
  (
    24,
    'Gym Heroes Booster Box',
    'Focuses on the Kanto Gym Leaders and their signature Pokémon. A nostalgic trip back to the original anime and games.',
    10250.00,
    'Eng',
    'Vintage',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuC4KwVqKSwPUGOlvjpreBqF-nNiXkv2OmviQFtWmIPVpZOcMiXeegrfQ62yWCU-3bHS2cF5GGbAyUQkcrFwLmwUdtSA3931NSlul9As2l-wjBNzvVhhzD2hRps__fqiny2OzCf9PWM8i6tBvvN52cxuYAji1HR8QigjvgJsUeihP0m8b2qSRXPLD8x_2evVN1Mbcsf6HZGvV6d7qSx_nKQOc8wKHXBWCKFntCcFl0-AAQBIZqLe8phZQoeiWCVeNL5fhjAHYoeOzH8',
    array[]::text[],
    true,
    4.8,
    22
  ),
  (
    25,
    'Jungle (No Symbol) Booster Box',
    'A rare error print run of the Jungle set where the expansion symbol is missing from holo cards. A unique piece of history.',
    9800.00,
    'Eng',
    'Vintage',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDoNrjC2wPoQH34AYmU2KF-XozHbQiDygDsNtiUwsacYq-fs9IbuBFbPTnRJFn6AML2Iy-mSKabpSSjs-80Vr4NhGEPp7BsNjAxnw04LkP5LKlBfAaVwORvw-4cwHnOzrKegYCJgTueShr4CoKtVxGFWIaqmTCql6ys2S-r9mEmjyJSFZasHjhdYXs8EaHiw4gBHocDJ6pBdHHecwxXTpTmhZeuiE0R_fPpCpY0IfH50LYf_cMDr37_XoWgT3yLH6oGLpqo3ts9ZUc',
    array[]::text[],
    true,
    4.7,
    15
  ),
  (
    26,
    'Sun & Moon: Team Up Booster Box',
    'Pokémon-GX team up for battle! This set features massive Tag Team Pokémon-GX with incredible power.',
    140.00,
    'Eng',
    'Sun & Moon',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBb_ZTVCqdi-qWbgyr4dgu-J_EkPmViLb8-7FlCtKEjQoe5Y9NzYQO3212fBT1mxDHRbOQjAgJBfFR-IRDyiE_xF4u-0J2tIlJG_0QxML9UArYgSoa3SVZJgP1SsmOZvGdPkUfNubFiYgLp-1g83C-h7eHi_31_G5vQHtPTbXxj-8VEinq-pMexzAP5XdDHq3ntrqIfklHq_4Snp3Vm_JD01s_Hu8d5s78-YJvyeZUKIxPDU4D_A7UyPSJDBLUPFRmW9761tDNY9kU',
    array[]::text[],
    true,
    4.9,
    65
  ),
  (
    27,
    'Sun & Moon: Unified Minds Booster Box',
    'To stay on top, your team must work as one! Unified Minds features more Tag Team Pokémon-GX and powerful new trainers.',
    450.00,
    'Eng',
    'Sun & Moon',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBxylXo0yARhd9EpABUW1UPaOBtmfAcRvHywbUu8I04moixpyucE19hzW7qjeAGIJ5W-0T8U8VW-XYHVZFMI4edworeX6ZS2aQVgpneYZiQiyljCEoggXsgCrUHEFbWwKXn7T96-6HqWRoXTP2xttaDUjnfkxshBKPCIhY8jb56X05XcMbBfHJ-swG1L5kmcTHXOTcWYsBVQ-GgN_m-3d4reiLe4HieH8omdTJSHliz1XQ_jpkBdfx6dA9AJw_o5D6W5G5z2Jco9aA',
    array[]::text[],
    true,
    4.8,
    42
  )
on conflict (id) do nothing;
